namespace Randolph.UI {
    /* This is autogenerated.
     Instead of adding a cursor HERE, search for "t:cursordatabase" object */

    /// <summary>Cursor names autogenerated by the Cursor Database.</summary>
    public enum Cursors {

        // autogenerated

    }
}
